validates:
  users:
    name_maximum: 50
    email_maximum: 255
    password_minium: 6
def_perpage: 5
def_page: 1
checkbox_true: "1"
def_image: "/uploads/category/image/88/download.jpeg"
val_price: 0
step_price: 0.5
type_post: ["admin", "user"]
val_day_default: 1
val_default: 0
column_content: 3
category_default: 3
