validates:
  users:
    name_maximum: 50
    email_maximum: 255
    password_minium: 6
def_perpage: 5
def_page: 1
checkbox_true: "1"
def_image: "/uploads/category/image/88/download.jpeg"
category_default: 3
